In [1]:
%matplotlib inline

from __future__ import print_function
import numpy as np
import statsmodels.api as sm
import pandas as pd
from statsmodels.tsa.arima_process import arma_generate_sample
np.random.seed(12345)

In [2]:
arparams = np.array([0])
maparams = np.array([.65, .35])

In [3]:
arparams = np.r_[1, -arparams]
maparam = np.r_[1, maparams]
nobs = 250
y = arma_generate_sample(arparams, maparams, nobs)

In [4]:
#Create a random time series to be used as exogenous variable
exog = np.random.normal(size=nobs)

In [5]:
dates = sm.tsa.datetools.dates_from_range('1980m1', length=nobs)
y = pd.TimeSeries(y, index=dates)
arma_mod = sm.tsa.ARMA(y, order=(0, 2), exog=exog)
arma_res = arma_mod.fit(trend='nc', disp=-1)

/Users/dbrodsky/Envs/bi-default/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: TimeSeries is deprecated. Please use Series
  from ipykernel import kernelapp as app


In [6]:
print(arma_res.summary())

                              ARMA Model Results                              
Dep. Variable:                      y   No. Observations:                  250
Model:                     ARMA(0, 2)   Log Likelihood                -245.420
Method:                       css-mle   S.D. of innovations              0.645
Date:                Wed, 08 Jun 2016   AIC                            498.839
Time:                        19:18:00   BIC                            512.925
Sample:                    01-31-1980   HQIC                           504.508
                         - 10-31-2000                                         
                 coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
x1             0.0099      0.033      0.302      0.763        -0.054     0.074
ma.L1.y        0.6287      0.062     10.140      0.000         0.507     0.750
ma.L2.y        0.0986      0.063      1.567      0.1

In [7]:
#Forecast
f_exog = [10, 10, 10, 10, 10]
f_exog_2 = [x * 5 for x in f_exog]

In [8]:
forecast_1 = arma_res.forecast(steps=5, exog=f_exog)[0]
forecast_1

array([-0.0884847 , -0.03223685, -0.00190045, -0.00860229,  0.0987421 ])

In [9]:
forecast_2 = arma_res.forecast(steps=5, exog=f_exog_2)[0]
forecast_2

array([-0.0884847 , -0.03223685, -0.00190045, -0.00860229,  0.49371049])

In [10]:
forecast_1 - forecast_2

array([ 0.        ,  0.        ,  0.        ,  0.        , -0.39496839])